### ISSUE TITLE
Restoring from an external mnemonic yields "has an invalid prefix" when scanning "classic" receive addr

### ISSUE THREAD

**Issue by kdmukai** [louisinger/silentium#8]
Presumably this is a bug caused by the changes in https://github.com/louisinger/silentium/commit/ce2494b62d4ce8da3a3f100c74621c16d2fda830

* Generate a new mnemonic outside of Silentium
* "Restore" it in Silentium
* Each "Sync" attempt will report that the "classic" receive addr "has an invalid prefix".

```
wallet.tsx:194 Error: tb1pwmt85qf4ydyg5sup9twmz3pnyjkfrepxpnuddv9vnv4yp50z4gfsp4k94a has an invalid prefix
    at Object.toOutputScript (address.js:135:1)
    at reloadWallet (wallet.tsx:164:1)
```

**Comment by louisinger** [comment]
Made some cleaning, [this](https://github.com/louisinger/silentium/commit/89b58fc39b0bf4b160ed810e133bb356f0accfc9#diff-7ffdcf520b7b8c28cb3c13a1784b87ecd5bc804a0c2da80e40b81b531c1d4223R160) should fix ?

**Comment by kdmukai** [comment]
Yes, now able to sync a "restored" mnemonic.

However, for one of my test mnemonics:
* I had previously received some testnet coins via the previous "classic" receive addr (the older one that did not match the expected 0th receive addr).
* And yesterday I did an internal cycle to spend some coins back to the same wallet (Silentium reuses the "classic" addr so I was sending back to the same addr, plus some going to a change output).
* After the latest updates, I can now scan and restore this wallet, HOWEVER, I only see txs related to the change output. The wallet does not recognize any utxos or txs related to the original "classic" receive addr.

Observations / Thoughts:
* The change output from yesterday does NOT match the expected 0th change output either; presumably it also used the same approach as the "classic" receive addr that needed to be altered.
* But since that change addr activity IS visible in the wallet, the change side must be missing the update in the wallet that was applied to the receive addr.
* And so, not surprisingly, a new change addr created AFTER the code changes is still not one of the expected change addrs for that mnemonic.
* Anyone who performed txs with the "classic" receive addr prior to the last 12hrs would now be cut off from accessing any remaining utxos. No big deal for testnet, obv not acceptable for mainnet.
* Need some sort of migration path to recover any orphaned utxos.

**Comment by louisinger** [comment]
Indeed, the old "wrong" address is not re-generated while restoring a new wallet. Still possible to run a version prior to the fix to restore a wallet with funds locked on the "wrong" address.

All change outputs are using the silent payments scheme, they are not using the P2TR address.

Also note that the fix introduced by last commits is backward compatible (It means that if u received coins on the "wrong" address, you are able to spend it even if the new P2TR address is fixed).
